steps:
- name: 'maven:3.6.1-jdk-8'
  entrypoint: 'mvn'
  args: ['clean', 'deploy', '-DaltDeploymentRepository=support.hln.com-snapshots::default::https://support.hln.com/artifactory/libs-snapshot-local']
  dir: '.'